CREATE TABLE Fact_Trip (
    trip_key INT IDENTITY(1,1) PRIMARY KEY,
    trip_uid VARCHAR(200),
    trip_status VARCHAR(50),
    trip_type VARCHAR(50),
    surge_multiplier VARCHAR(20),
    price_usd VARCHAR(20),
    distance_kms VARCHAR(20),
    trip_time VARCHAR(50),
    total_time VARCHAR(50),
    wait_time VARCHAR(50),
    date_key INT,
    driver_key INT,
    vehicle_key INT,
    location_key INT,
    weather_key INT,
    rider_key INT,
    accm_txn_create_time DATETIME,
    accm_txn_complete_time DATETIME,
    txn_process_time_hours FLOAT,
    FOREIGN KEY (date_key) REFERENCES Dim_Date(date_key),
    FOREIGN KEY (driver_key) REFERENCES Dim_Driver(driver_key),
    FOREIGN KEY (vehicle_key) REFERENCES Dim_Vehicle(vehicle_key),
    FOREIGN KEY (location_key) REFERENCES Dim_Location(location_key),
    FOREIGN KEY (weather_key) REFERENCES Dim_Weather(weather_key),
    FOREIGN KEY (rider_key) REFERENCES Dim_Rider(rider_key)
)